export const predefinedProviders: ModelProvider[] = [
  {
    active: true,
    apiKey: "",
    name: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    apiKeyHelpUrl: "https://platform.openai.com/account/api-keys",
    baseUrlHelpUrl: "https://platform.openai.com/docs/api-reference/chat/create",
    provider: "openai",
    models: [],
  },
  {
    active: true,
    apiKey: "",
    name: "Anthropic",
    apiKeyHelpUrl: "https://console.anthropic.com/settings/keys",
    baseUrl: "https://api.anthropic.com/v1",
    provider: "anthropic",
    baseUrlHelpUrl: "https://docs.anthropic.com/en/api/messages",
    models: [],
  },
  {
    active: true,
    apiKey: "",
    name: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    apiKeyHelpUrl: "https://openrouter.ai/settings/keys",
    baseUrlHelpUrl: "https://openrouter.ai/docs/api-reference/overview",
    provider: "openrouter",
    models: [],
  },
  {
    active: true,
    apiKey: "",
    name: "Grok",
    baseUrl: "https://api.x.ai/v1",
    apiKeyHelpUrl: "https://console.x.ai/team/default/api-keys",
    baseUrlHelpUrl: "https://docs.x.ai/docs/models",
    provider: "grok",
    models: [],
  },
  {
    active: true,
    apiKey: "",
    name: "Gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    apiKeyHelpUrl: "https://aistudio.google.com/apikey",
    baseUrlHelpUrl: "https://ai.google.dev/gemini-api/docs/openai",
    provider: "gemini",
    models: [],
  },
  {
    active: true,
    apiKey: "",
    name: "DeepSeek",
    baseUrl: "https://api.deepseek.com/v1",
    apiKeyHelpUrl: "https://platform.deepseek.com/api_keys",
    baseUrlHelpUrl: "https://api-docs.deepseek.com",
    provider: "deepseek",
    models: [],
  },
  // ==================== 国内提供商 ====================
  {
    active: false,
    apiKey: "",
    name: "智谱 GLM",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    apiKeyHelpUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    baseUrlHelpUrl: "https://open.bigmodel.cn/dev/api/normal-model/glm-4",
    provider: "zhipu",
    models: [],
  },
  {
    active: false,
    apiKey: "",
    name: "KIMI (Moonshot)",
    baseUrl: "https://api.moonshot.cn/v1",
    apiKeyHelpUrl: "https://platform.moonshot.cn/console/api-keys",
    baseUrlHelpUrl: "https://platform.moonshot.cn/docs/api/chat",
    provider: "kimi",
    models: [],
  },
  {
    active: false,
    apiKey: "",
    name: "小米 MiMo",
    baseUrl: "https://api.xiaomimimo.com/v1",
    apiKeyHelpUrl: "https://platform.xiaomimimo.com",
    baseUrlHelpUrl: "https://platform.xiaomimimo.com",
    provider: "xiaomi",
    models: [],
  },
  {
    active: false,
    apiKey: "",
    name: "阿里百炼 (Qwen)",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    apiKeyHelpUrl: "https://bailian.console.aliyun.com/#/api-key",
    baseUrlHelpUrl: "https://help.aliyun.com/zh/model-studio/compatibility-with-openai",
    provider: "qwen",
    models: [],
  },
  {
    active: false,
    apiKey: "",
    name: "豆包 (火山方舟)",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    apiKeyHelpUrl: "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
    baseUrlHelpUrl: "https://www.volcengine.com/docs/82379/1263512",
    provider: "doubao",
    models: [],
  },
];
